name: draftmode_ui
description: Handle Dialogs with autoConfirm.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  draftmode_localization: ^1.0.0

dependency_overrides:
  draftmode_localization:
    path: ../localization

dev_dependencies:     
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  test: ^1.26.2

flutter:
  uses-material-design: true


repository: https://github.com/draftm0de/flutter.ui
issue_tracker: https://github.com/draftm0de/flutter.ui/issues

