name: draftmode_ui
description: Handle Dialogs with autoConfirm.
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: "3.35.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  draftmode_localization:
    git: https://github.com/draftm0de/flutter.localization
    version: ^1.0.0

dev_dependencies:     
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  test: ^1.26.2

flutter:
  uses-material-design: true

repository: https://github.com/draftm0de/flutter.ui
issue_tracker: https://github.com/draftm0de/flutter.ui/issues
